// <auto-generated />
using System;
using AuditSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuditSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260406150824_update-properties")]
    partial class updateproperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Audit_System.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1f1f1f1-1111-1111-1111-f1f1f1f1f1f1"),
                            Action = "INSERT",
                            EntityId = "00000000-0000-0000-0000-000000000001",
                            EntityName = "User",
                            Metadata = "Initial System Admin Created.",
                            Timestamp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("f2f2f2f2-2222-2222-2222-f2f2f2f2f2f2"),
                            Action = "INSERT",
                            EntityId = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
                            EntityName = "User",
                            Metadata = "Admin created user: Ali",
                            Timestamp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("f3f3f3f3-3333-3333-3333-f3f3f3f3f3f3"),
                            Action = "INSERT",
                            EntityId = "b2c3d4e5-f6a7-5b8c-9d0e-1f2a3b4c5d6e",
                            EntityName = "User",
                            Metadata = "Admin created user: Sara",
                            Timestamp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("f4f4f4f4-4444-4444-4444-f4f4f4f4f4f4"),
                            Action = "INSERT",
                            EntityId = "c1c1c1c1-1111-1111-1111-c1c1c1c1c1c1",
                            EntityName = "Course",
                            Metadata = "Created Course: C# Basics",
                            Timestamp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("f5f5f5f5-5555-5555-5555-f5f5f5f5f5f5"),
                            Action = "INSERT",
                            EntityId = "c2c2c2c2-2222-2222-2222-c2c2c2c2c2c2",
                            EntityName = "Course",
                            Metadata = "Created Course: ASP.NET Core",
                            Timestamp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("f6f6f6f6-6666-6666-6666-f6f6f6f6f6f6"),
                            Action = "INSERT",
                            EntityId = "c3c3c3c3-3333-3333-3333-c3c3c3c3c3c3",
                            EntityName = "Course",
                            Metadata = "Created Course: Entity Framework Core",
                            Timestamp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("f7f7f7f7-7777-7777-7777-f7f7f7f7f7f7"),
                            Action = "ENROLL",
                            EntityId = "e1e1e1e1-1111-1111-1111-e1e1e1e1e1e1",
                            EntityName = "Enrollment",
                            Metadata = "Ali enrolled in C# Basics",
                            Timestamp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d")
                        },
                        new
                        {
                            Id = new Guid("f8f8f8f8-8888-8888-8888-f8f8f8f8f8f8"),
                            Action = "ENROLL",
                            EntityId = "e2e2e2e2-2222-2222-2222-e2e2e2e2e2e2",
                            EntityName = "Enrollment",
                            Metadata = "Ali enrolled in ASP.NET Core",
                            Timestamp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d")
                        },
                        new
                        {
                            Id = new Guid("f9f9f9f9-9999-9999-9999-f9f9f9f9f9f9"),
                            Action = "ENROLL",
                            EntityId = "e3e3e3e3-3333-3333-3333-e3e3e3e3e3e3",
                            EntityName = "Enrollment",
                            Metadata = "Sara enrolled in ASP.NET Core",
                            Timestamp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("b2c3d4e5-f6a7-5b8c-9d0e-1f2a3b4c5d6e")
                        },
                        new
                        {
                            Id = new Guid("fafafafa-aaaa-aaaa-aaaa-fafafafafafa"),
                            Action = "ENROLL",
                            EntityId = "e4e4e4e4-4444-4444-4444-e4e4e4e4e4e4",
                            EntityName = "Enrollment",
                            Metadata = "Sara enrolled in Entity Framework Core",
                            Timestamp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("b2c3d4e5-f6a7-5b8c-9d0e-1f2a3b4c5d6e")
                        });
                });

            modelBuilder.Entity("Audit_System.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1c1c1c1-1111-1111-1111-c1c1c1c1c1c1"),
                            Author = "Suzanne Collin",
                            Description = "Learn the fundamentals of C# programming.",
                            Price = 200m,
                            Title = "C# Basics"
                        },
                        new
                        {
                            Id = new Guid("c2c2c2c2-2222-2222-2222-c2c2c2c2c2c2"),
                            Author = "Andrew Lock",
                            Description = "Build web applications using ASP.NET Core.",
                            Price = 200m,
                            Title = "ASP.NET Core"
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-3333-3333-3333-c3c3c3c3c3c3"),
                            Author = "Julia Lerman",
                            Description = "Master data access with Entity Framework Core.",
                            Price = 300m,
                            Title = "Entity Framework Core"
                        });
                });

            modelBuilder.Entity("Audit_System.Domain.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1e1e1e1-1111-1111-1111-e1e1e1e1e1e1"),
                            CourseId = new Guid("c1c1c1c1-1111-1111-1111-c1c1c1c1c1c1"),
                            Timestamp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d")
                        },
                        new
                        {
                            Id = new Guid("e2e2e2e2-2222-2222-2222-e2e2e2e2e2e2"),
                            CourseId = new Guid("c2c2c2c2-2222-2222-2222-c2c2c2c2c2c2"),
                            Timestamp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d")
                        },
                        new
                        {
                            Id = new Guid("e3e3e3e3-3333-3333-3333-e3e3e3e3e3e3"),
                            CourseId = new Guid("c2c2c2c2-2222-2222-2222-c2c2c2c2c2c2"),
                            Timestamp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("b2c3d4e5-f6a7-5b8c-9d0e-1f2a3b4c5d6e")
                        },
                        new
                        {
                            Id = new Guid("e4e4e4e4-4444-4444-4444-e4e4e4e4e4e4"),
                            CourseId = new Guid("c3c3c3c3-3333-3333-3333-c3c3c3c3c3c3"),
                            Timestamp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("b2c3d4e5-f6a7-5b8c-9d0e-1f2a3b4c5d6e")
                        });
                });

            modelBuilder.Entity("Audit_System.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Email = "admin@gmail.com",
                            Name = "Admin",
                            PasswordHash = "Admin@123"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            Email = "ali@gmail.com",
                            Name = "Ali",
                            PasswordHash = "Ali@123"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-5b8c-9d0e-1f2a3b4c5d6e"),
                            Email = "sara@gmail.com",
                            Name = "Sara",
                            PasswordHash = "Sara@123"
                        });
                });

            modelBuilder.Entity("Audit_System.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("Audit_System.Domain.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Audit_System.Domain.Entities.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Audit_System.Domain.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Audit_System.Domain.Entities.User", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
